hcmuslib/Controllers/LibrarianController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using hcmuslib.Models;
using PagedList;

namespace hcmuslib.Controllers
{
    [Authorize(Roles = "ReaderManager")]
    public class LibrarianController : Controller
    {
        //
        // GET: /Librarian/
        QLTHUVIENEntities data = new QLTHUVIENEntities();

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult BarcodeReader()
        {
            return View();
        }
        public ActionResult Analytics()
        {
            return View();
        }

        public ActionResult ManageReaderImage(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var docgia = from p in data.DOCGIA select p;

            if (!String.IsNullOrEmpty(searchString))
            {
                docgia = docgia.Where(p => p.MS_THE.Contains(searchString));
            }
            
            switch (sortOrder)
            { 
                case "name_desc":
                    docgia = docgia.OrderByDescending(p => p.HO_TEN);
                    break;
                default:
                    docgia = docgia.OrderBy(p => p.HO_TEN);
                    break;
            }

            int pageSize = 20;
            int pageNumber = (page ?? 1);
            return View(docgia.ToPagedList(pageNumber, pageSize));
        }

        [AttributeUsage(AttributeTargets.Method, AllowMultiple = false, Inherited = true)]
        public class MultipleButtonAttribute : ActionNameSelectorAttribute
        {
            public string Name { get; set; }
            public string Argument { get; set; }

            public override bool IsValidName(ControllerContext controllerContext, string actionName, System.Reflection.MethodInfo methodInfo)
            {
                var isValidName = false;
                var keyValue = string.Format("{0}:{1}", Name, Argument);
                var value = controllerContext.Controller.ValueProvider.GetValue(keyValue);

                if (value != null)
                {
                    controllerContext.Controller.ControllerContext.RouteData.Values[Name] = Argument;
                    isValidName = true;
                }

                return isValidName;
            }
        }

        public ActionResult BackToAll()
        {
            return RedirectToAction("ManageReaderImage");
        }

        [HttpPost]
        [MultipleButton(Name = "action", Argument = "Upload")]
        public ActionResult Upload(FormCollection f, HttpPostedFileBase file)
        {
            if (file != null && file.ContentLength > 0)
            {
                var MST = f["mathe"];
                DOCGIA result = (from p in data.DOCGIA where p.MS_THE == MST select p).First();

                var fileName = string.Format("avatar-{0}.png", result.MS_THE);
                var path = Path.Combine(Server.MapPath("~/Images/profilePic"), fileName);
                file.SaveAs(path);

                result.IMAGE_URL = fileName;
                data.SaveChanges();
            }
            return RedirectToAction("ManageReaderImage");
        }

        [HttpPost]
        [MultipleButton(Name = "action", Argument = "Remove")]
        public ActionResult Remove(FormCollection f)
        {
            var MST = f["mathe"];
            DOCGIA result = (from p in data.DOCGIA where p.MS_THE == MST select p).First();

            string current = Request.MapPath("~/Images/profilePic/" + result.IMAGE_URL);
            if (System.IO.File.Exists(current))
            {
                System.IO.File.Delete(current);
            }

            result.IMAGE_URL = null;
            data.SaveChanges();
            
            return RedirectToAction("ManageReaderImage");
        }

        //public ActionResult BookReturningHome() 
        //{
        //    string maDG = Request["madg"];
        //    string action = Request["action"];
        //    if (Request.IsAjaxRequest())
        //    {
        //        switch (action) {
        //            case "show":
        //                 var lh = from l in data.LUUHANHSACH
        //                     where l.DOC_GIA == maDG && l.TINH_TRANG.Equals("0")
        //                     select l;
        //                if (lh.Any())
        //                {
        //                    return PartialView("_BookReturningDetail", lh.ToList());
        //                }
        //                else {
        //                    return PartialView("_BookReturningNotFound");
        //                }
        //            case "confirm": 
        //                string lhid = Request["lhid"];
        //                var lh1 = (from l in data.LUUHANHSACH
        //                        where l.ID_LUU_HANH == lhid
        //                        select l).First();
        //                lh1.TINH_TRANG = "1";
        //                data.SaveChanges();
        //                return PartialView("_ReturnConfirmMessage");
        //            case "punishment":
        //                string bid = Request["bid"];
        //                string status = Request["status"];
        //                Random ran = new Random(12);
        //                string str = ran.Next(0, 99999999).ToString();
        //                string id = "BT"+str.PadLeft(8, '0');
        //                var findid = (from b in data.BOITHUONGTHIETHAI
        //                             where b.ID_BOI_THUONG == id
        //                             select b).ToList();
                        
        //                while (findid.Count != 0) {
                           
        //                    str = ran.Next(0, 99999999).ToString();
        //                    id = "BT" + str.PadLeft(8, '0');
        //                    findid = (from b in data.BOITHUONGTHIETHAI
        //                            where b.ID_BOI_THUONG == id
        //                            select b).ToList();
        //                }
                        
        //                BOITHUONGTHIETHAI bt = new BOITHUONGTHIETHAI 
        //                {   
        //                    ID_BOI_THUONG = id,
        //                    ID_VAT_BOI_THUONG = bid,
        //                    DOC_GIA = maDG,
        //                    LY_DO = status,
        //                    NGAY_BOI_THUONG=DateTime.Now,
        //                    TINH_TRANG = "1"
        //                };
        //                data.BOITHUONGTHIETHAI.Add(bt);
        //                data.SaveChanges();
        //                return PartialView("_PunishmentConfirm");

        //        }   
        //    }
        //    return View();
        //}


    }
}

hcmuslib/Views/Librarian/Analytics.cshtml
@{
    ViewBag.Title = "Analytics";
    Layout = "~/Views/Shared/_Layout_librarian.cshtml";
}

 <section id="title" class="emerald">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <h1>Thống kê đọc giả</h1>
                    <p>Pellentesque habitant morbi tristique senectus et netus et malesuada</p>
                </div>
                <div class="col-sm-6">
                    <ul class="breadcrumb pull-right">
                        <li><a href="@Url.Action("index","librarian")">Quản lý độc giả</a></li>
                        
                        <li class="active">Thống kê đọc giả</li>
                    </ul>
                </div>
            </div>
        </div>
    </section><!--/#title-->    

    <section class="container">
		<div class="row">
			<div class="col-md-2">
				<label for="analytic-type">Chọn tiêu chí thống kê</label>
			</div>
			<div class="col-md-3">
				<select class="form-control" name="analytic-type" id="analytic-type">
					<option>Giới tính</option>
					<option>Loại</option>
					<option>3</option>
					<option>4</option>
					<option>5</option>
				</select>
			</div>
		</div>
		<div class="gap"></div>
		<div class="row">
			<div id="sex-chart" style="width:100%; height:400px;"></div>
			<div id="type-chart" style="width:100%; height:400px;"></div>
		</div>
    </section><!--/#terms-->
@section charts {
<script type="text/javascript">
		jQuery(function ($) {
			$('#type-chart').highcharts({
				chart: {
					plotBackgroundColor: null,
					plotBorderWidth: 1,//null,
					plotShadow: false
				},
				title: {
					text: 'Thống kê đọc giả theo loại'
				},
				tooltip: {
					pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
				},
				plotOptions: {
					pie: {
						allowPointSelect: true,
						cursor: 'pointer',
						dataLabels: {
							enabled: true,
							format: '<b>{point.name}</b>: {point.percentage:.1f} %',
							style: {
								color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
							}
						}
					}
				},
				series: [{
					type: 'pie',
					name: 'Browser share',
					data: [
						['Sinh viên',   60],
						['Ngoài đại học',       10],
						['Cán bộ',       30],
					]
				}],
				colors: ['#7cb5ec', '#90ed7d','#910000']
			});
		});
			
		jQuery(function ($) {
			$('#sex-chart').highcharts({
				chart: {
					plotBackgroundColor: null,
					plotBorderWidth: 1,//null,
					plotShadow: false
				},
				title: {
					text: 'Thống kê đọc giả theo giới tính'
				},
				tooltip: {
					pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
				},
				plotOptions: {
					pie: {
						allowPointSelect: true,
						cursor: 'pointer',
						dataLabels: {
							enabled: true,
							format: '<b>{point.name}</b>: {point.percentage:.1f} %',
							style: {
								color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
							}
						}
					}
				},
				series: [{
					type: 'pie',
					name: 'Browser share',
					data: [
						['Nam',   55],
						['Nữ',       45],
					]
				}],
				colors: ['#7cb5ec', '#90ed7d']
			});
		});
		
		</script>
    }

hcmuslib/Views/Librarian/BarcodeReader.cshtml
@{
    ViewBag.Title = "BarcodeReader";
    Layout = "~/Views/Shared/_Layout_librarian.cshtml";
}

<script src="@Url.Content("~/Scripts/jquery.min.js")"></script>

<script src="@Url.Content("~/Scripts/jquery.webcamqrcode.min.js")"></script>
<script>
    (function ($) {
        $('document').ready(function () {

            $('#qrcodebox').WebcamQRCode({
                onQRCodeDecode: function (p_data) {

                    $('#qrcode_result').html(p_data);
                }
            });

            $('#btn_start').click(function () {
                $('#qrcodebox').WebcamQRCode().start();
            });

            $('#btn_stop').click(function () {
                $('#qrcodebox').WebcamQRCode().stop();
            });
        });
    })(jQuery);
</script>


<section id="title" class="emerald">
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <h1>Đọc mã</h1>
                <p>Pellentesque habitant morbi tristique senectus et netus et malesuada</p>
            </div>
            <div class="col-sm-6">
                <ul class="breadcrumb pull-right">
                    <li><a href="@Url.Action("index","librarian")">Quản lý độc giả</a></li>
                    <li class="active">Đọc mã</li>
                </ul>
            </div>
        </div>
    </div>
</section><!--/#title-->

<section class="container">
    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-primary" style="width:380px">
                <div class="panel-heading">
                    <h3 class="panel-title">Camera</h3>
                </div>
                <div class="panel-body">
                    <div class="camera" style="height:360px;">
                        
                        <div style="width: 350px; height: 350px;" id="qrcodebox">
                           
                        </div>
                        <input type="button" value="Start" id="btn_start" />
                        <input type="button" value="Stop" id="btn_stop" />

                        <p>
                            Last QRCode value: <span id="qrcode_result">none</span>
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-5 col-md-offset-1">
            <div class="col-md-6">
                <img src="@Url.Content("~/images/team-member.jpg")" alt="" class="img-thumbnail">
            </div>
            <div class="col-md-6">
                <p><strong>Mã DG:</strong> DG00001</p>
                <p><strong>Thông tin:</strong> Thông tin</p>
            </div>
        </div>
    </div>
</section><!--/#terms-->

hcmuslib/Views/Librarian/Index.cshtml
@{
    ViewBag.Title = "Quản lý độc giả";
    Layout = "~/Views/Shared/_Layout_librarian.cshtml";
}

<section id="title" class="emerald">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <h1>Trang chủ - Quản lý độc giả</h1>
                    
                </div>
                <div class="col-sm-6">
                    <ul class="breadcrumb pull-right">
                        <li><a href="@Url.Action("index","librarian")">Quản lý độc giả</a></li>
                        <li class="active">Trang chủ</li>
                    </ul>
                </div>
            </div>
        </div>
    </section><!--/#title-->     

    <section id="services">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="center gap">
                        <h2>Chức năng của bộ phận Quản lý độc giả</h2>
                        
                    </div>                
                </div>
            </div>
            <div class="row">
				<div class="col-md-4 col-sm-6">
					<div class="gly-link"><a href="@Url.Action("analytics","librarian")"><h3><span class="glyphicon glyphicon-send gly-bigger"></span>Thống kê độc giả theo tiêu chí</h3></a></div>
					<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae.</p>                
                </div><!--/.col-md-4-->
				 <div class="col-md-4 col-sm-6">
					<div class="gly-link"><a href="@Url.Action("managereaderimage","librarian")"><h3><span class="glyphicon glyphicon-book gly-bigger"></span>Quản lý hình ảnh độc giả</h3></a></div>
					<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae.</p>      
                </div><!--/.col-md-4-->
                <div class="col-md-4 col-sm-6">
                    <div class="gly-link"><a href="@Url.Action("barcodereader","librarian")"><h3><span class="glyphicon glyphicon-th gly-bigger"></span>Đọc mã vạch</h3></a></div>
					<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae.</p>      
                </div><!--/.col-md-4-->
               
               
            </div><!--/.row-->
           @* <div class="gap"></div>
             <div class="row">
				<div class="col-md-4 col-sm-6">
					<div class="gly-link"><a href="librarian_manage_book.html"><h3><span class="glyphicon glyphicon-info-sign gly-bigger"></span> Quản lý sách</h3></a></div>
					<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae.</p>      
                </div><!--/.col-md-4-->*@
                
               
            </div><!--/.row-->
            <hr>
           @* <div class="row">
                <div class="col-lg-12">
                    <div class="center">
                        <h2>What our clients say</h2>
                        <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>
                    </div>
                    <div class="gap"></div>
                    <div class="row">
                        <div class="col-md-6">
                            <blockquote>
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
                                <small>Someone famous in <cite title="Source Title">Source Title</cite></small>
                            </blockquote>
                        </div>
                        <div class="col-md-6">
                            <blockquote>
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
                                <small>Someone famous in <cite title="Source Title">Source Title</cite></small>
                            </blockquote>
                        </div>
                    </div>
                </div>
            </div>*@
    </section><!--/#services-->

hcmuslib/Views/Librarian/ManageReaderImage.cshtml
@model PagedList.IPagedList<hcmuslib.Models.DOCGIA>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Manage Reader Image";
    Layout = "~/Views/Shared/_Layout_librarian.cshtml";
}

<section id="title" class="emerald">
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <h1>Quản lý hình ảnh</h1>
                <p>Pellentesque habitant morbi tristique senectus et netus et malesuada</p>
            </div>
            <div class="col-sm-6">
                <ul class="breadcrumb pull-right">
                    <li><a href="@Url.Action("index","librarian")">Quản lý độc giả</a></li>
                    <li class="active">Quản lý hình ảnh</li>
                </ul>
            </div>
        </div>
    </div>
</section>
<!--/#title-->

<section class="container">
    <form action="/Librarian/ManageReaderImage" method="get"class="form-horizontal" role="form">
        <div class="form-group">
            <label class="col-md-2 control-label" for="searchString">Mã độc giả</label>
            <div class="col-md-3">
                <input type="text" class="form-control" name="searchString" value="@ViewBag.CurrentFilter"/>
            </div>
            <div class="col-md-1">
                <input type="submit" class="btn btn-success"  value="Tìm kiếm" />
            </div>
            <div class="col-md-1">
                <button class="btn btn-danger">@Html.ActionLink("Sắp xếp", "ManageReaderImage", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })</button>
            </div>
            <div class="col-md-1">
                <button class="btn btn-danger">@Html.ActionLink("Tất cả", "BackToAll")</button>
            </div>
        </div>
    </form>
    <div class="gap"></div>
    @{var i = 1;}
    @foreach (var item in Model)
    {
        if (i % 4 == 1)
        {
            @:<div class="row">
        }
            @:<div class="col-md-3">
				@:<div class="row">
					@:<div class="col-md-6">
                        if (item.IMAGE_URL == null)
                        { 
                            @:<img src="@Url.Content("~/Images/noavatar.png")" alt="" class="img-thumbnail" />
                        }
                        else
                        {
                            @:<img src="@Url.Content("~/Images/profilePic/" + item.IMAGE_URL)" alt="" class="img-thumbnail" />
                        }
					@:</div>
					@:<div class="col-md-6">
						@:<p>@item.MS_THE</p>
						@:<p>@item.HO_TEN</p>
					@:</div>
				@:</div>
				@:<div class="row">
                    using (Html.BeginForm(null, "Librarian", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        <input type="file" name="file" /><br />
                        <input type="hidden" name="mathe" value="@item.MS_THE">
                        <div class="row">
                            <div class="col-md-3"><input type="submit" class="btn btn-default btn-sm" name="action:Upload" value="Upload" /></div>
                            <div class="col-md-3"><input type="submit" class="btn btn-default btn-sm" name="action:Remove" value="Remove" /></div>
                        </div>
                    }                    
		        @:</div>
		    @:</div>
        if (i % 4 == 0)
        {
            @:</div><div class="gap"></div>
        }
        i++;
    }
    <div class="gap"></div>
    <p>
        Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
        @Html.PagedListPager(Model, page => Url.Action("ManageReaderImage", new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
    </p>
</section>
<!--/#terms-->

hcmuslib/Views/Librarian/Search.cshtml
@model IEnumerable<hcmuslib.Models.DOCGIA>
@{
    ViewBag.Title = "Search Reader Image";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section id="title" class="emerald">
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <h1>Quản lý hình ảnh</h1>
                <p>Pellentesque habitant morbi tristique senectus et netus et malesuada</p>
            </div>
            <div class="col-sm-6">
                <ul class="breadcrumb pull-right">
                    <li><a href="index.html">Home</a></li>
                    <li><a href="#">Pages</a></li>
                    <li class="active">Quản lý hình ảnh</li>
                </ul>
            </div>
        </div>
    </div>
</section>
<!--/#title-->

<section class="container">
    <form action="/Librarian/Search" method="post" class="form-horizontal" role="form">
        <div class="form-group">
            <label class="col-md-2 control-label" for="id-reader">Mã độc giả</label>
            <div class="col-md-3">
                <input type="text" class="form-control" name="id-reader" />
            </div>
            <div class="col-md-1">
                <input type="submit" class="btn btn-success" name="action:Search" value="Tìm kiếm" />
            </div>
            <div class="col-md-1">
                <input type="submit" class="btn btn-success" name="action:BackToAll" value="Tất cả" />
            </div>
        </div>
    </form>
    <div class="gap"></div>
    @{var i = 1;}
    @foreach (var item in Model)
    {
        if (i % 4 == 1)
        {
            @:<div class="row">
        }
            @:<div class="col-md-3">
				@:<div class="row">
					@:<div class="col-md-6">
                        if (item.IMAGE_URL == null)
                        { 
                            @:<img src="@Url.Content("~/Images/noavatar.png")" alt="" class="img-thumbnail" />
                        }
                        else
                        {
                            @:<img src="@Url.Content("~/Images/profilePic/" + item.IMAGE_URL)" alt="" class="img-thumbnail" />
                        }
					@:</div>
					@:<div class="col-md-6">
						@:<p>@item.MS_THE</p>
						@:<p>@item.HO_TEN</p>
					@:</div>
				@:</div>
				@:<div class="row">
                    using (Html.BeginForm(null, "Librarian", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        <input type="file" name="file" /><br />
                        <input type="hidden" name="mathe" value="@item.MS_THE">
                        <div class="row">
                            <div class="col-md-3"><input type="submit" class="btn btn-default btn-sm" name="action:Upload" value="Upload" /></div>
                            <div class="col-md-3"><input type="submit" class="btn btn-default btn-sm" name="action:Remove" value="Remove" /></div>
                        </div>
                    }                    
		        @:</div>
		    @:</div>
        if (i % 4 == 0)
        {
            @:</div><div class="gap"></div>
        }
        i++;
    }
</section>
<!--/#terms-->