hcmuslib/Controllers/LibrarianSupporterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using hcmuslib.Models;
using System.Data.Entity;
using System.Data.Entity.Core.Objects;
using PagedList;
namespace hcmuslib.Controllers
{
    [Authorize(Roles = "ReaderSupporter")]
    public class LibrarianSupporterController : Controller
    {
        //
        // GET: /LibrarianSupporter/
        QLTHUVIENEntities data = new QLTHUVIENEntities();

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult SendMail(string id_dg, string ngay_tra)
        {
            var viewResult = ViewMS() as ActionResult;
            //if (viewResult != null)
            //{
            //    viewResult.ViewName = "~/Views/Home/Contact.cshtml";
            //}
            var dg = (from d in data.DOCGIA where d.MS_THE == id_dg select d).First();
            EMail oMail = new EMail();
            oMail.SendMail("Email", dg.EMAIL, new String[] { "Nhắc Nhở Trả Sách Thư Viện ĐH Khoa Học Tự Nhiên", "Chào bạn, hệ thống thư viện nhắc nhở bạn ngày " + ngay_tra + " là đến hạn trả sách mà bạn đang mượn vui lòng thực hiện đúng như yêu cầu. Cám ơn"});
            
            return viewResult;
        }

        public ActionResult ViewMS()
        {                      
            return View();
        }
        public PartialViewResult AjaxApi_ViewMS(string MSType,string keySearch, string CurrentFilter, string CurrentType , int? page)
        {
            var ms = from d in data.LUUHANHSACH.AsNoTracking() select d;
            ViewBag.MsType0 = "selected";  
            if(keySearch != null)
            {
                page = 1;
            }
            else
            {
                keySearch = CurrentFilter;
            }
            if (MSType != null)
            {
                page = 1;
            }
            else
            {
                MSType = CurrentType;
            }
            ViewBag.CurrentFilter = keySearch;
            ViewBag.CurrentType = MSType;
            if (keySearch == null)
                keySearch = "";
            switch (MSType)
            {
                case "0":

                    ms = from d in data.LUUHANHSACH.AsNoTracking()
                         where d.ID_LUU_HANH.Contains(keySearch) || d.DOC_GIA.Contains(keySearch)
                             || d.ID_SACH.Contains(keySearch)
                         select d;
                    break;
                case "1":
                    ViewBag.MsType1 = "selected";
                    ViewBag.MsType0 = "";
                    
                    ms = from d in data.LUUHANHSACH.AsNoTracking()
                         where d.TINH_TRANG == "1" && (d.ID_LUU_HANH.Contains(keySearch) || d.DOC_GIA.Contains(keySearch)
                             || d.ID_SACH.Contains(keySearch))
                         select d;
                    break;
                case "2":
                    ViewBag.MsType2 = "selected";
                    ViewBag.MsType0 = "";
                    ms = from d in data.LUUHANHSACH.AsNoTracking()
                         where (d.TINH_TRANG == "0" && d.THOI_HAN_MUON <= DateTime.Today) && (d.ID_LUU_HANH.Contains(keySearch) || d.DOC_GIA.Contains(keySearch)
                             || d.ID_SACH.Contains(keySearch))
                         select d;
                    break;
                case "3":
                    ViewBag.MsType3 = "selected";
                    ViewBag.MsType0 = "";
                    ms = from d in data.LUUHANHSACH.AsNoTracking()
                         where (d.TINH_TRANG == "0" && d.THOI_HAN_MUON >= DateTime.Today
                             && DateTime.Today >= DbFunctions.AddDays(d.THOI_HAN_MUON, -2)) && (d.ID_LUU_HANH.Contains(keySearch) || d.DOC_GIA.Contains(keySearch)
                         || d.ID_SACH.Contains(keySearch))
                         select d;
                    break;
                default:
                    ms = (from d in data.LUUHANHSACH.AsNoTracking() select d);
                    break;
            }
            int pageSize = 8;
            int pageNumber = (page ?? 1);
            
            var list_ms = ms.ToList();
            @ViewBag.Count = list_ms.Count;
            return PartialView("AjaxApi_ViewMS", list_ms.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult TrainingManagement() 
        {
            if (Request.IsAjaxRequest()) 
            {
                string action = Request["action"];
                string tmtype = Request["tmtype"];
                string tt = "0";
                switch (tmtype)
                {
                    case "requested":
                        tt = "0";
                        break;
                    case "pending":
                        tt = "1";
                        break;
                    case "trained":
                        tt = "2";
                        break;
                }               
                if (action == "tmview")
                {
                    var tha = (from t in data.TAPHUAN
                              where t.TINH_TRANG == tt
                               select t).OrderByDescending(t => t.NGAY_DANG_KY);
                    if (tha.Any())
                    {
                        ViewBag.type = tt;
                        return PartialView("_TrainingTableView", tha.ToList());
                    }
                    else
                    {
                        return PartialView("_TrainingNotFound");
                    }
                }
                if (action == "adddate") {
                    int day = Convert.ToInt16(Request["day"]);
                    int month = Convert.ToInt16(Request["month"]);
                    int year = Convert.ToInt16(Request["year"]);
                    int number = Convert.ToInt16(Request["number"]);
                    DateTime dt = new DateTime(year, month, day);
                    var tha = (from t in data.TAPHUAN
                              where t.TINH_TRANG == "0"
                               select t).OrderByDescending(t => t.NGAY_DANG_KY);
                    var thal = tha.Take(number);
                    if (thal.Any())
                    {
                        foreach (var item in thal) 
                        {
                            item.NGAY_DANG_KY = dt;
                            item.TINH_TRANG = "1";
                        }
                        data.SaveChanges();
                        ViewBag.type = "0";
                        return PartialView("_TrainingTableView", tha.ToList());
                    }
                    
                }
               
            }
            var th = (from t in data.TAPHUAN
                     where t.TINH_TRANG == "0"
                     select t).OrderByDescending(t => t.NGAY_DANG_KY);           
            return View(th.ToList());            
        }
    }
}

hcmuslib/Views/LibrarianSupporter/AjaxApi_ViewMS.cshtml
@model PagedList.IPagedList<hcmuslib.Models.LUUHANHSACH>
@using PagedList.Mvc;

@if(Model != null)
{
    if (Model.Count() != 0)
    {
        <div class="status alert alert-success">Tìm thấy @ViewBag.Count kết quả phù hợp !</div>
        <table class="table table-bordered" id="ListMS">
            <tr>
                <th>
                    @Html.DisplayName("ID Lưu Hành")
                </th>
                <th>
                    @Html.DisplayName("ID Độc giả")
                </th>
                <th>
                    @Html.DisplayName("ID Sách")
                </th>
                <th>
                    @Html.DisplayName("Ngày Mượn")
                </th>
                <th>
                    @Html.DisplayName("Thời Hạn Trả")
                </th>
                <th>
                    @Html.DisplayName("Tình Trạng")
                </th>
                <td id="td_nn" style="display:none">
                    @Html.DisplayName("Nhắc Nhở")
                </td>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.ID_LUU_HANH)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DOC_GIA)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ID_SACH)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NGAY_MUON)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.THOI_HAN_MUON)
                    </td>
                    <td>
                        @if (item.TINH_TRANG == "1")
                        {
                            @Html.DisplayName("Đã trả");
                        }
                        else
                        {
                           @Html.DisplayName("Đang mượn");                           
                        }
                    </td>
                </tr>
            }

        </table>
    }
    else
    {
        <div class="status alert alert-success">Không Tìm Thấy Kết Quả Nào Phù Hợp ?!</div>
    }
    <br />

   

        @Html.PagedListPager(@Model, page => Url.Action("AjaxApi_ViewMS",
                       new { page, CurrentType = @ViewBag.CurrentType, CurrentFilter = @ViewBag.CurrentFilter }),
                       PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(
                       new AjaxOptions(){
                           UpdateTargetId = "content_table",
                           HttpMethod = "Post",
                           InsertionMode = InsertionMode.Replace,
                           LoadingElementId = "loader"
                       }
                       ));
}
        

hcmuslib/Views/LibrarianSupporter/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout_librariansupporter.cshtml";
}

<section id="title" class="emerald">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <h1>Trang chủ - Hỗ trợ độc giả</h1>
                    
                </div>
                <div class="col-sm-6">
                    <ul class="breadcrumb pull-right">
                        <li><a href="@Url.Action("index","librariansupporter")">Hỗ trợ độc giả</a></li>
                        <li class="active">Trang chủ</li>
                    </ul>
                </div>
            </div>
        </div>
    </section><!--/#title-->     

    <section id="services">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="center gap">
                        <h2>Chức năng của bộ phận Hỗ trợ độc giả</h2>
                        
                    </div>                
                </div>
            </div>
            <div class="row">
				<div class="col-md-4 col-sm-6">
					<div class="gly-link"><a href="@Url.Action("trainingmanagement","librariansupporter")"><h3><span class="glyphicon glyphicon-send gly-bigger"></span>Quản lý đăng ký tập huấn</h3></a></div>
					<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae.</p>                
                </div><!--/.col-md-4-->
				 <div class="col-md-4 col-sm-6">
					<div class="gly-link"><a href="@Url.Action("viewms","librariansupporter")"><h3><span class="glyphicon glyphicon-book gly-bigger"></span>Quản lý mượn sách</h3></a></div>
					<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae.</p>      
                </div><!--/.col-md-4-->
@*                <div class="col-md-4 col-sm-6">
                    <div class="gly-link"><a href="@Url.Action("barcodereader","librarian")"><h3><span class="glyphicon glyphicon-th gly-bigger"></span>Độc mã vạch</h3></a></div>
					<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae.</p>      
                </div><!--/.col-md-4-->*@
               
               
            </div><!--/.row-->
           @* <div class="gap"></div>
             <div class="row">
				<div class="col-md-4 col-sm-6">
					<div class="gly-link"><a href="librarian_manage_book.html"><h3><span class="glyphicon glyphicon-info-sign gly-bigger"></span> Quản lý sách</h3></a></div>
					<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae.</p>      
                </div><!--/.col-md-4-->*@
                
               
            </div><!--/.row-->
            <hr>
           @* <div class="row">
                <div class="col-lg-12">
                    <div class="center">
                        <h2>What our clients say</h2>
                        <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>
                    </div>
                    <div class="gap"></div>
                    <div class="row">
                        <div class="col-md-6">
                            <blockquote>
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
                                <small>Someone famous in <cite title="Source Title">Source Title</cite></small>
                            </blockquote>
                        </div>
                        <div class="col-md-6">
                            <blockquote>
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
                                <small>Someone famous in <cite title="Source Title">Source Title</cite></small>
                            </blockquote>
                        </div>
                    </div>
                </div>
            </div>*@
        </div>
    </section><!--/#services-->

hcmuslib/Views/LibrarianSupporter/TrainingManagement.cshtml
@model IEnumerable<hcmuslib.Models.TAPHUAN>
@{
    ViewBag.Title = "TrainingManagement";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section id="title" class="emerald">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <h1>Hỗ trợ đọc giả - Đăng kí tập huấn</h1>
                    <p>Pellentesque habitant morbi tristique senectus et netus et malesuada</p>
                </div>
                <div class="col-sm-6">
                    <ul class="breadcrumb pull-right">
                        <li><a href="index.html">Home</a></li>
                        <li><a href="#">Pages</a></li>
                        <li class="active">Hỗ trợ đọc giả - Đăng kí tập huấn</li>
                    </ul>
                </div>
            </div>
        </div>
    </section><!--/#title-->    

    <section class="container" id="tm-container">
		<div class="row">
			<div class="col-md-3">
				<select class="form-control" id="tm-view-type">
					<option value="requested">Gửi yêu cầu tập huấn</option>
					<option value="pending">Đang chờ tập huấn</option>
					<option value="trained">Đã tập huấn</option>
				</select>
			</div>
		</div>
        <div id="request-info">
		    <div class="row">
				    <div class="col-md-2">
					    <p><strong>Nhập ngày tập huấn</strong></p>
				    </div>
				    <div class="col-md-1">
					    <form class="form-horizontal" role="form">
						    <div class="col-md-12">
							    <div class="form-group">							
								    <input type="text" class="form-control" id="day" placeholder="Ngày">
							    </div>
						    </div>
					    </form>
				    </div>
				    <div class="col-md-2">
					    <form class="form-horizontal" role="form">
						    <div class="col-md-8">
							    <div class="form-group">
								    <select class="form-control" id="month">
									    <option value="1">Tháng 1</option>
									    <option value="2">Tháng 2</option>
									    <option value="3">Tháng 3</option>
									    <option value="4">Tháng 4</option>
									    <option value="5">Tháng 5</option>
									    <option value="6">Tháng 6</option>
									    <option value="7">Tháng 7</option>
									    <option value="8">Tháng 8</option>
									    <option value="9">Tháng 9</option>
									    <option value="10">Tháng 10</option>
									    <option value="11">Tháng 11</option>
									    <option value="12">Tháng 12</option>
								    </select>							
							    </div>
						    </div>
					    </form>
				    </div>
				    <div class="col-md-1 col-md-pull-1">
					    <form class="form-horizontal" role="form">
						    <div class="col-md-12 col-md-push-7">
							    <div class="form-group">							
								      <input type="text" class="form-control" id="year" placeholder="Năm">
							    </div>
						    </div>
					    </form>
				    </div>
				    <div class="col-md-3 col-md-push-1">
					    <form class="form-horizontal" role="form">
						    <div class="form-group">
							    <label for="number" class="col-md-4 control-label">Số lượng</label>
							    <div class="col-md-5">
							      <input type="text" class="form-control" id="number" placeholder="Số lượng">
							    </div>
						    </div>
					    </form>
				    </div>
				    <div class="col-md-1 col-md-push-1">
					    <button type="button" class="btn btn-success" id="training-btn">Xác nhận</button>
				    </div>
		    </div>
		    <div class="row text-center">
			
			    <p>Chọn "ngày tập huấn" cho "số lượng" người gửi yêu cầu đăng kí trong danh sách tính từ trên xuống</p>
			
		    </div>
        </div>
        <div id="tm-view-container">
		    <table class="table table-bordered">
			    <tr>
				    <th>STT</th>
				    <th>Họ tên</th>
				    <th>SDT</th>
				    <th>Email</th>
				    <th>Ngày tập huấn</th>
				    <th>Tình trạng</th>
			    </tr>
                @{int i = 1;}
                @foreach (var item in Model) 
                {
			    <tr>
                    <td>@i</td>
				    <td>@item.HO_TEN</td>
                    <td>@item.SDT</td>
                    <td>@item.EMAIL</td>
                    <td>Chờ chọn ngày</td>
                    <td class="danger">Gửi đăng kí</td>
			    </tr>
                    i++;
                }
		    </table>
        </div>
    </section><!--/#terms-->

hcmuslib/Views/LibrarianSupporter/ViewMS.cshtml
@{
    ViewBag.Title = "ViewMS";
    
}
<head>
    <title>Theo Doi Muon Sach - Thư viện ĐH KHTN TPHCM</title>
    <link href="/Content/bootstrap.min.css" rel="stylesheet">
    <link href="/Content/font-awesome.min.css" rel="stylesheet">
    <link href="/Content/prettyPhoto.css" rel="stylesheet">
    <link href="/Content/animate.css" rel="stylesheet">
    <link href="/Content/main.css" rel="stylesheet">
    <link href="/Content/mystyle.css" rel="stylesheet">
    <script type="text/javascript" src="~/Scripts/jquery.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
</head>
<section id="title4" class="emerald">
    
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <h1>Theo dõi mượn sách</h1>
               
            </div>
            <div class="col-sm-6">
                <ul class="breadcrumb pull-right">
                    <li><a href="index.html">Home</a></li>
                    <li><a href="#">Pages</a></li>
                    <li class="active"><a href="#">Theo dõi mượn sách</a></li>
                </ul>
            </div>
        </div>
    </div>
</section><!--/#title-->
<section id="theo_doi_muon_sach" class="container">
    <div class="row">
        <h3>Danh sách  </h3>
        @using (Ajax.BeginForm("AjaxApi_ViewMS", "LibrarianSupporter", new AjaxOptions 
        { 
            UpdateTargetId = "content_table", 
            HttpMethod = "Post",
            //InsertionMode = InsertionMode.Replace,
            LoadingElementId = "loader"
        }))
        {
            string keySearch = "";
            <h6>Tìm Kiếm Theo ID Lưu Hành, ID Độc Giả, ID Sách: </h6>
            <div style="width:200px;height:30px">
                @Html.TextBoxFor(m => keySearch, new { @class = "form-control" })              
                <input id="hid_btn" type="submit" style="display:none" />
            </div>
            <h6>Trên: </h6>
            <select class="form-control" style="width:200px;height:30px" id="mySelect" name="MSType" onchange="OnChangeMSType();">
                <option value="0" selected=@ViewBag.MsType0>All</option>
                <option value="1" selected=@ViewBag.MsType1>Đã trả</option>
                <option value="2" selected=@ViewBag.MsType2>Đang mượn</option>
                <option value="3" selected=@ViewBag.MsType3>Gần đến hạn</option>
            </select>
            <br />
            <br />
        }  
                   

        </div>
        <script>
            $(document).ready(function () {
                $('select').change(function () {
                    $("select option:selected").each(function () {
                        if($(this).val() == "Gần đến hạn")
                            $('#td_n').style.display = "normal"
                    })                  
                })
            });
            function OnChangeMSType() {
                $('#hid_btn').click();
            }
        </script>
        <div id="content_table">
            <div id="loader" class=" aletr" style="display:none">
                <br />
                <br />
                <img src="~/Images/ajax-loader.gif" width="200" height="200" />
            </div>
            <div>

            </div>
            @Html.Action("AjaxApi_ViewMS")
            @Html.Partial("AjaxApi_ViewMS")

        </div>
</section>>

hcmuslib/Views/LibrarianSupporter/_TrainingNotFound.cshtml
<p>Không tìm thấy kết quả nào</p>

hcmuslib/Views/LibrarianSupporter/_TrainingTableView.cshtml
@model IEnumerable<hcmuslib.Models.TAPHUAN>
<table class="table table-bordered">
    <tr>
	    <th>STT</th>
	    <th>Họ tên</th>
	    <th>SDT</th>
	    <th>Email</th>
	    <th>Ngày tập huấn</th>
	    <th>Tình trạng</th>
    </tr>
    @{int i = 1;}
    @{string type = ViewBag.type;}
    @{string tttext = "";}
    @{string status = "";}
    @switch (type)
    {
        case "0":
            tttext = "Gửi đăng kí";
            status = "danger";
            break;
        case "1":
            tttext = "Chờ tập huấn";
            status = "warning";
            break;
        case "2":
            tttext = "Đã tập huấn";
            status = "success";
            break;
    }
    @foreach (var item in Model) 
    {
        
    <tr>
        <td>@i</td>
	    <td>@item.HO_TEN</td>
        <td>@item.SDT</td>
        <td>@item.EMAIL</td>
        @if (type == "0") {
        <td>Chờ chọn ngày</td>
        }else{
        <td>@item.NGAY_DANG_KY</td>
        }
        <td class="@status">@tttext</td>
    </tr>
        i++;
    }
</table>

hcmuslib/Views/LibrarianSupporter/selectMSType.cshtml
@model IEnumerable<hcmuslib.Models.LUUHANHSACH>

@{
    ViewBag.Title = "selectMSType";
}

<h2>Theo doi Muon Sach </h2>

<form id="myForm" action="/LibrarianSupporter/selectMSType" method="post">
    <select id="mySelect" name="MSType" onchange="OnchangeMSType();">
        <option value="0" selected="selected">All</option>
        <option value="1">Hoan Thanh</option>
        <option value="2">Da Hoan Thanh</option>
        <option value="3">Gan Den Han</option>
    </select>
</form>

<script>
    function OnchangeMSType() {
        $('#myForm').submit();
    }
</script>

<table class="table table-bordered" id="ListMS">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ID_LUU_HANH)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DOC_GIA)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ID_SACH)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NGAY_MUON)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.THOI_HAN_MUON)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TINH_TRANG)
        </th>
        @*<th></th>*@
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ID_LUU_HANH)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DOC_GIA)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ID_SACH)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NGAY_MUON)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.THOI_HAN_MUON)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TINH_TRANG)
            </td>
            @*<td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>*@
        </tr>
    }

</table>